disabled_rules:
- identifier_name
opt_in_rules:
 - function_body_length
 - multiple_closures_with_trailing_closure
 - cyclomatic_complexity
 - empty_count
 - trailing_whitespace
excluded:
  - Pods
force_cast: warning
force_try:
  severity: warning
cyclomatic_complexity: 
 warning: 10
 error: 30
line_length: 120
type_body_length:
  - 100
  - 300
file_length:
  warning: 300
  error: 500
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 70
  excluded: iPhone
reporter: "xcode"